version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  salve_patinhas:
    image: salve_patinhas
    build: .
    depends_on:
      - postgresql
    ports:
      - '8081:8081'
    environment:
      - DATABASE_URL=postgresql://postgres@postgresql:5432/postgres
    command: bash -c "alembic upgrade head && uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 8081"
    volumes:
      - .:/app


volumes:
  postgresql_data:
    driver: local